#!/bin/bash

groupmod -o -g ${PGID} tissue-plus
usermod -o -u ${PUID} tissue-plus

chown -R tissue-plus:tissue-plus /app

umask ${UMASK}

nginx
gosu tissue-plus:tissue-plus alembic upgrade head && gosu tissue-plus:tissue-plus uvicorn app.main:app --log-level warning