'''
Author: Await
Date: 2025-05-26 23:43:22
LastEditors: Await
LastEditTime: 2025-05-26 23:44:07
Description: 请填写简介
'''
"""add is_paused field to actor_subscribe

Revision ID: 0eb776dce68b
Revises: b3e0bc8903cd
Create Date: 2025-05-26 23:43:22.368968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb776dce68b'
down_revision: Union[str, None] = 'b3e0bc8903cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor_subscribe', sa.Column('is_paused', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor_subscribe', 'is_paused')
    # ### end Alembic commands ###
