"""fix torrent model - add is_hd field and fix hash type

Revision ID: 20250109_fix_torrent
Revises: b3e0bc8903cd
Create Date: 2025-01-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250109_fix_torrent'
down_revision = 'b3e0bc8903cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 修改hash字段类型从Integer改为String
    op.alter_column('torrent', 'hash',
                    existing_type=sa.Integer(),
                    type_=sa.String(50),
                    existing_nullable=False)
    
    # 添加is_hd字段
    op.add_column('torrent', sa.Column('is_hd', sa.Boolean(), nullable=False, server_default='0'))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除is_hd字段
    op.drop_column('torrent', 'is_hd')
    
    # 恢复hash字段类型为Integer
    op.alter_column('torrent', 'hash',
                    existing_type=sa.String(50),
                    type_=sa.Integer(),
                    existing_nullable=False)
    
    # ### end Alembic commands ###