"""fix torrent model - add is_hd field and fix hash type

Revision ID: 20250109_fix_torrent
Revises: b3e0bc8903cd
Create Date: 2025-01-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250109_fix_torrent'
down_revision = 'b3e0bc8903cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # SQLite不支持ALTER COLUMN，需要重新创建表
    # 但是如果表还不存在，我们可以直接跳过
    try:
        # 检查表是否存在
        conn = op.get_bind()
        result = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='torrent'")
        if result.fetchone() is None:
            # 表不存在，跳过修改
            return
        
        # 添加is_hd字段（如果还没有）
        try:
            op.add_column('torrent', sa.Column('is_hd', sa.Boolean(), nullable=False, server_default='0'))
        except Exception:
            # 字段可能已经存在
            pass
        
        # 对于hash字段类型修改，我们先检查当前类型
        # 如果是Integer类型，需要重新创建表
        inspector = sa.inspect(conn)
        columns = inspector.get_columns('torrent')
        hash_column = next((col for col in columns if col['name'] == 'hash'), None)
        
        if hash_column and str(hash_column['type']).upper().startswith('INTEGER'):
            # 需要重新创建表
            op.rename_table('torrent', 'torrent_old')
            
            # 创建新表
            op.create_table('torrent',
                sa.Column('id', sa.Integer(), primary_key=True),
                sa.Column('name', sa.String(255), nullable=False),
                sa.Column('hash', sa.String(50), nullable=False),
                sa.Column('magnet', sa.Text(), nullable=False),
                sa.Column('size', sa.String(20), nullable=True),
                sa.Column('is_hd', sa.Boolean(), nullable=False, server_default='0'),
                sa.Column('create_by', sa.String(50), nullable=True),
                sa.Column('create_time', sa.DateTime(), nullable=True),
                sa.Column('update_by', sa.String(50), nullable=True),
                sa.Column('update_time', sa.DateTime(), nullable=True),
            )
            
            # 复制数据
            op.execute("INSERT INTO torrent (id, name, hash, magnet, size, is_hd, create_by, create_time, update_by, update_time) "
                      "SELECT id, name, CAST(hash AS TEXT), magnet, size, 0, create_by, create_time, update_by, update_time FROM torrent_old")
            
            # 删除旧表
            op.drop_table('torrent_old')
            
    except Exception as e:
        # 如果出错，可能是表结构已经正确，忽略错误
        pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除is_hd字段
    op.drop_column('torrent', 'is_hd')
    
    # 恢复hash字段类型为Integer
    op.alter_column('torrent', 'hash',
                    existing_type=sa.String(50),
                    type_=sa.Integer(),
                    existing_nullable=False)
    
    # ### end Alembic commands ###