'''
Author: Await
Date: 2025-05-26 01:13:26
LastEditors: Await
LastEditTime: 2025-05-26 16:40:33
Description: 请填写简介
'''
"""add actor subscribe tables

Revision ID: 2af387d41608
Revises: 296fa8c2261d
Create Date: 2025-05-26 01:13:26.290651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af387d41608'
down_revision: Union[str, None] = '296fa8c2261d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
