"""添加订阅包含和排除关键字

Revision ID: 383104710481
Revises: 9135e6d48625
Create Date: 2025-06-22 10:36:10.116128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
<<<<<<< HEAD
from sqlalchemy.engine.reflection import Inspector
=======
>>>>>>> upstream/main


# revision identifiers, used by Alembic.
revision: str = '383104710481'
down_revision: Union[str, None] = '9135e6d48625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
<<<<<<< HEAD
    # 获取数据库连接和检查器
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # 检查表是否存在
    if 'subscribe' in inspector.get_table_names():
        # 获取现有列
        existing_columns = [col['name'] for col in inspector.get_columns('subscribe')]

        # 只在列不存在时添加
        if 'include_keyword' not in existing_columns:
            op.add_column('subscribe', sa.Column('include_keyword', sa.String(), nullable=True))
        if 'exclude_keyword' not in existing_columns:
            op.add_column('subscribe', sa.Column('exclude_keyword', sa.String(), nullable=True))


def downgrade() -> None:
    # 获取数据库连接和检查器
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # 检查表和列是否存在
    if 'subscribe' in inspector.get_table_names():
        existing_columns = [col['name'] for col in inspector.get_columns('subscribe')]
        if 'exclude_keyword' in existing_columns:
            op.drop_column('subscribe', 'exclude_keyword')
        if 'include_keyword' in existing_columns:
            op.drop_column('subscribe', 'include_keyword')
=======
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('include_keyword', sa.String(), nullable=True))
    op.add_column('subscribe', sa.Column('exclude_keyword', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'exclude_keyword')
    op.drop_column('subscribe', 'include_keyword')
    # ### end Alembic commands ###
>>>>>>> upstream/main
